import { OptionItem } from "../../core/interfaces/option.interface";

export const FILTER_OPTIONS: Record<string, OptionItem[]> = {
  'FILTERS.SELECT.ORDER_BY': [
    { label: 'FILTERS.OPTIONS.ORDER_BY.RECENT', value: 'recent', text: 'FILTERS.OPTIONS.ORDER_BY.RECENT'},
    { label: 'FILTERS.OPTIONS.ORDER_BY.OLDEST', value: 'oldest', text: 'FILTERS.OPTIONS.ORDER_BY.OLDEST'}
  ],
  'FILTERS.SELECT.LOCATION': [
    { label: 'FILTERS.OPTIONS.LOCATION.REMOTE', value: 'remote', text: 'FILTERS.OPTIONS.LOCATION.REMOTE' },
    { label: 'FILTERS.OPTIONS.LOCATION.ONSITE', value: 'onsite', text: 'FILTERS.OPTIONS.LOCATION.ONSITE' },
    { label: 'FILTERS.OPTIONS.LOCATION.HYBRID', value: 'hybrid', text: 'FILTERS.OPTIONS.LOCATION.HYBRID' }
  ],
  'FILTERS.SELECT.WORK_TYPE': [
    { label: 'FILTERS.OPTIONS.WORK_TYPE.FULL_TIME', value: 'full_time', text: 'FILTERS.OPTIONS.WORK_TYPE.FULL_TIME' },
    { label: 'FILTERS.OPTIONS.WORK_TYPE.PART_TIME', value: 'part_time', text: 'FILTERS.OPTIONS.WORK_TYPE.PART_TIME' },
    { label: 'FILTERS.OPTIONS.WORK_TYPE.FREELANCE', value: 'freelance', text: 'FILTERS.OPTIONS.WORK_TYPE.FREELANCE' }
  ],
  'FILTERS.SELECT.EXPERIENCE': [
    { label: 'FILTERS.OPTIONS.EXPERIENCE.NONE', value: 'none', text: 'FILTERS.OPTIONS.EXPERIENCE.NONE' },
    { label: 'FILTERS.OPTIONS.EXPERIENCE.ONE_TO_THREE', value: '1_3', text: 'FILTERS.OPTIONS.EXPERIENCE.ONE_TO_THREE' },
    { label: 'FILTERS.OPTIONS.EXPERIENCE.MORE_THAN_THREE', value: '3_plus', text:'FILTERS.OPTIONS.EXPERIENCE.MORE_THAN_THREE' }
  ],
  'FILTERS.SELECT.SALARY': [
    { label: 'FILTERS.OPTIONS.SALARY.ONE_THOUSAND', value: 'lt_1000', text: 'FILTERS.OPTIONS.SALARY.ONE_THOUSAND' },
    { label: 'FILTERS.OPTIONS.SALARY.TWO_THOUSAND', value: 'gt_2000', text: 'FILTERS.OPTIONS.SALARY.TWO_THOUSAND' },
    { label: 'FILTERS.OPTIONS.SALARY.THREE_THOUSAND', value: 'gt_3000', text: 'FILTERS.OPTIONS.SALARY.THREE_THOUSAND' }
  ],
  'FILTERS.SELECT.WORK_MODE': [
    { label: 'FILTERS.OPTIONS.WORK_MODE.MORNING', value: 'morning', text: 'FILTERS.OPTIONS.WORK_MODE.MORNING'},
    { label: 'FILTERS.OPTIONS.WORK_MODE.AFTERNOON', value: 'afternoon', text: 'FILTERS.OPTIONS.WORK_MODE.AFTERNOON'},
    { label: 'FILTERS.OPTIONS.WORK_MODE.NIGHT', value: 'night', text: 'FILTERS.OPTIONS.WORK_MODE.NIGHT'}
  ]
};
